/*
 * OGE Tutor App — shared constants.
 * Navigation and domain filters use backend contract status codes, not UI labels.
 */
import { HOMEWORK_STATUS, LESSON_STATUS, STUDENT_ROUTE, TEACHER_ROUTE } from '../api/contracts.js';

export const STUDENT_NAV_ITEMS = [
  STUDENT_ROUTE.HOME,
  STUDENT_ROUTE.HOMEWORK,
  STUDENT_ROUTE.LESSONS,
  STUDENT_ROUTE.MATERIALS,
  STUDENT_ROUTE.PROGRESS,
  STUDENT_ROUTE.PROFILE,
];

export const TEACHER_NAV_ITEMS = [
  TEACHER_ROUTE.HOME,
  TEACHER_ROUTE.STUDENTS,
  TEACHER_ROUTE.SCHEDULE,
  TEACHER_ROUTE.HOMEWORK,
  TEACHER_ROUTE.MATERIALS,
  TEACHER_ROUTE.PROFILE,
];

export const PROFILE_BACKGROUNDS = ['blue', 'violet', 'emerald', 'rose', 'amber', 'slate'];

export const HOMEWORK_FILTERS = [
  { value: 'all', label: 'Все' },
  { value: HOMEWORK_STATUS.ASSIGNED, label: 'Назначено' },
  { value: HOMEWORK_STATUS.SUBMITTED, label: 'Сдано' },
  { value: HOMEWORK_STATUS.NEEDS_REVISION, label: 'На доработке' },
  { value: HOMEWORK_STATUS.REVIEWED, label: 'Проверено' },
  { value: HOMEWORK_STATUS.OVERDUE, label: 'Просрочено' },
];

export const ACTIVE_LESSON_STATUSES = [LESSON_STATUS.PLANNED, LESSON_STATUS.RESCHEDULED];
export const HISTORY_LESSON_STATUSES = [LESSON_STATUS.COMPLETED, LESSON_STATUS.CANCELED];
export const EDITABLE_HOMEWORK_STATUSES = [HOMEWORK_STATUS.ASSIGNED, HOMEWORK_STATUS.OVERDUE, HOMEWORK_STATUS.NEEDS_REVISION];
export const STUDENT_SUBMITTABLE_HOMEWORK_STATUSES = [HOMEWORK_STATUS.ASSIGNED, HOMEWORK_STATUS.NEEDS_REVISION, HOMEWORK_STATUS.OVERDUE];
